### ISSUE TITLE
Проверка Лабы 1

### ISSUE THREAD

**Issue by KuroOnee** [KuroOnee/helloworld#1]
Переделал. Вроде теперь как надо.

To: @evgeny-p

**Comment by evgeny-p** [comment]
Для сохранения истории дублирую замечания, которые были к первоначальному варианту:

>  [март 06 09:49] **evgeny-p**
> Первая часть работы предполагает два сценария слияния веток:
> 1. Мерж с --no-ff. Соответствует стандартному рабочему процессу.
> 2. Мерж с разрешением конфликта.
> 
> У Вас выполнен только второй пункт.

Сейчас все выполнено в соответствии с заданием.
Только заголовок сбивает: это первая часть второй лабораторной, а в заголовке задачи указана первая работа.

Эту задачу можно закрывать. Вторую часть работы лучше выполнять в отдельном репозитории.

**Comment by KuroOnee** [comment]
Теперь понял. Будем делать.
